feat: add multi language
CleverCodeLabs/resume-it pull request #11
Opened 2023-03-29 17:08 UTC by joellemantey

2023-03-30 14:49 UTC, tnhnkzc commented on apps/web/components/languages/LanguagesForm.tsx
> +          <Select placeholder="Select option" {...field}>
Tu as regardé pour le soucis de pouvoir choisir le placeholder en tant qu'une option?

2023-03-30 14:50 UTC, tnhnkzc commented on apps/web/components/languages/LanguagesForm.tsx
> +    console.log("submit");
console.log à supprimer

2023-03-30 14:52 UTC, tnhnkzc requested changes
- Supprimer le "console.log",
- Regarder le soucis de placeholder

2023-03-30 15:06 UTC, joellemantey commented on apps/web/components/languages/LanguagesForm.tsx
> +          <Select placeholder="Select option" {...field}>
oui il ne le prend pas en compte. je vais le modifer et mettre "sélectionner votre niveau"

2023-03-31 06:07 UTC, philwronski approved these changes

2023-03-31 06:19 UTC, merged